src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wakad Level 3</fullName>
            </value>
            <value>
                <fullName>Baner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/classes/ValidateBookingRecordTest.cls
@isTest
public class ValidateBookingRecordTest {
    @TestSetup static void initData(){
        Conference_Room__c confRec = new Conference_Room__c(Name = 'Test Conference Room', Active__c = true, Capacity__c = 2,
                                                             	Location__c ='Baner');
        insert confRec;
        
        Booking_Detail__c bookingRec = new Booking_Detail__c(Name = 'Test Booking Detail', Duration__c = '1.0', Conference_Room__c = confRec.Id,
                                                            Start_Time__c = System.now(), Status__c = 'Booked');
        insert bookingRec;
    }
    
    @isTest static void test_Constructor(){
        test.startTest();
        ValidateBookingRecord rec = new ValidateBookingRecord();
        test.stopTest();
    }
    
    @isTest static void test_validateBookingRecr(){
        Conference_Room__c conRec = [Select Id, Name From Conference_Room__c Limit 1];
        Booking_Detail__c bookingRec = [Select Id, Name, Start_Time__c, Duration__c From Booking_Detail__c Limit 1];
        test.startTest();
        ValidateBookingRecord.validateBookingRec(String.valueOf(conRec.Id), bookingRec.Start_Time__c, bookingRec.Duration__c);
        test.stopTest();
    }
    
    @isTest static void test_fetchConfRoom(){
        Conference_Room__c conRec = [Select Id, Name From Conference_Room__c Limit 1];
        test.startTest();
        ValidateBookingRecord.fetchConfRoom(String.valueOf(conRec.Id));
        test.stopTest();
    }
}