src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wakad Level 3</fullName>
            </value>
            <value>
                <fullName>Baner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Booking_Detail__c.field-meta.xml
<CustomField>
    <fullName>Booking_Detail__c</fullName>
    <label>Booking Detail</label>
    <referenceTo>Booking_Detail__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/classes/BookingViewControllerTest.cls
@isTest
public class BookingViewControllerTest {

    @TestSetup
    static void makeData(){
        Conference_Room__c confRoom = new Conference_Room__c(Name='Test Room',Location__c='Wakad Level 3');
        insert confRoom;
        Booking_Detail__c bookingDetail = new Booking_Detail__c(Start_Time__c = System.now(),Name = 'Test Booking',Duration__c = '1.0',Conference_Room__c = confRoom.Id);
        insert bookingDetail;
    }

    @isTest
    public static void testGetLocations() {
        List<String> locations = BookingTimetableController.getAllLocations();
        System.assert(locations != NULL && locations.size() > 0);
    }

    @isTest
    public static void testGetRoomBySpecificLocAndDate() {
        List<Conference_Room__c> rooms = BookingTimetableController.getBookingsByDateAndTime(System.today(),'Wakad Level 3');
        System.assert(rooms != null && rooms.size() == 1 && rooms[0].Booking_Details__r != null && rooms[0].Booking_Details__r.size() == 1);
    }

    @isTest
    public static void testGetRoomByAllLocAndOtherDate() {
        List<Conference_Room__c> rooms = BookingTimetableController.getBookingsByDateAndTime(System.today().addDays(1),'All');
        System.assert(rooms != null && rooms.size() == 1 && rooms[0].Booking_Details__r != null && rooms[0].Booking_Details__r.size() == 0);
    }
    
    @isTest
    public static void testCreateParticipants() {
        Booking_Detail__c booking = [Select Id from Booking_Detail__c LIMIT 1];
        BookingTimetableController.createParticipantsFromBooking(booking.Id,new List<String>{UserInfo.getUserId()});
        List<Participant__c> guests = [Select Id from Participant__c];
        System.assertEquals(2, guests.size());
    }
}