src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wakad Level 3</fullName>
            </value>
            <value>
                <fullName>Baner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/classes/InsertBookingDetailTest.cls
@isTest
public class InsertBookingDetailTest {
    
    @TestSetup
    static void makeData(){
        Conference_Room__c confRoom = new Conference_Room__c(Name='Test Room',Location__c='Wakad Level 3',Capacity__c = 5);
        insert confRoom;
        
    }
    
    @isTest
    public static void testsaveBookingDetailRecord() {
        Conference_Room__c confRoom = [Select id from Conference_Room__c LIMIT 1];
        Booking_Detail__c bookingDetail = new Booking_Detail__c(Start_Time__c = System.now(),Name = 'Test Booking',Duration__c = '1.0',Conference_Room__c = confRoom.Id);
        InsertBookingDetail.saveBookingDetailRecord(bookingDetail);
    }
    
    @isTest
    public static void testFailsaveBookingDetailRecord() {
        Conference_Room__c confRoom = [Select id from Conference_Room__c LIMIT 1];
        Booking_Detail__c bookingDetail = new Booking_Detail__c(Name = 'Test Booking');
        try {
            InsertBookingDetail.saveBookingDetailRecord(bookingDetail);
        } catch(AuraHandledException ex) {
            
        }
        
    }

}