src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c  + ((VALUE(Text(Duration__c )) * 60) / 1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wakad Level 3</fullName>
            </value>
            <value>
                <fullName>Baner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Booking_Detail__c.field-meta.xml
<CustomField>
    <fullName>Booking_Detail__c</fullName>
    <label>Booking Detail</label>
    <referenceTo>Booking_Detail__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Guest__c.field-meta.xml
<CustomField>
    <fullName>Guest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creator</fullName>
            </value>
            <value>
                <fullName>Organizer</fullName>
            </value>
            <value>
                <fullName>Attendee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/classes/BookingTimetableController.cls
public without sharing class BookingTimetableController {
    
    //get room booking details for all rooms of a particular location
	//params:
	//locations: location selected
	//year,month and day of month: will be converted to appropriate Date class instance than sending date from javascript
    @AuraEnabled
    public static List<Conference_Room__c> getBookingsByDateAndTime(Date selectedDate,string selectedLocation){
        //Code will to generic helper method to get/set booking details
        string query = 'Select Id,Name,(Select Name,Start_Time__c,End_Time__c FROM Booking_Details__r where Booking_Date__c = :selectedDate) FROM Conference_Room__c';
        if(!selectedLocation.equalsIgnoreCase('All')) {
            query += ' WHERE Location__c =: selectedLocation';
        }
        List<Conference_Room__c> conferenceRoomsAndBookings = Database.query(query);
        return conferenceRoomsAndBookings;
    }

    //get all locations from picklist field on conference room object
    @AuraEnabled
    public static List<String> getAllLocations(){
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Conference_Room__c.Location__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }

    @AuraEnabled
    public static void createParticipantsFromBooking(string bookingId,List<string> userIds){
        if(String.isNotBlank(bookingId)) {
            List<Participant__c> participantsToInsert = new List<Participant__c>();
            Participant__c organiser = new Participant__c(Booking_Detail__c = bookingId,Guest__c = UserInfo.getUserId(),Role__c='Organizer');
            participantsToInsert.add(organiser);
            for(string userId : userIds) {
                Participant__c attendee = new Participant__c(Booking_Detail__c = bookingId,Guest__c = userId,Role__c='Attendee');
                participantsToInsert.add(attendee);
            }

            insert participantsToInsert;
        }
    }
}