src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c  + ((VALUE(Text(Duration__c )) * 60) / 1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Booking_Detail__c.field-meta.xml
<CustomField>
    <fullName>Booking_Detail__c</fullName>
    <label>Booking Detail</label>
    <referenceTo>Booking_Detail__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Can_Cancel_Booking__c.field-meta.xml
<CustomField>
    <fullName>Can_Cancel_Booking__c</fullName>
    <formula>IF( TEXT(Role__c) == &apos;Creator&apos; || TEXT(Role__c) == &apos;Organizer&apos; , true, false)</formula>
    <label>Can Cancel Booking?</label>
    <type>Checkbox</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Guest__c.field-meta.xml
<CustomField>
    <fullName>Guest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Participant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creator</fullName>
            </value>
            <value>
                <fullName>Organizer</fullName>
            </value>
            <value>
                <fullName>Attendee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/classes/BookingController.cls
public with sharing class BookingController {
    @AuraEnabled(cacheable=true)
    public static List<Participant__c> getParticipants() {
        DateTime dt = System.now();
        System.debug('dt :: ' + dt);
		return [Select Id,
				Booking_Detail__r.Id,
				Booking_Detail__r.Name,
				Booking_Detail__r.Start_Time__c,
				Booking_Detail__r.End_Time__c,
				Role__c,
				Can_Cancel_Booking__c,
				Booking_Detail__r.Conference_Room__r.Name				
				From Participant__c 
				Where Guest__c =: UserInfo.getUserId()
				AND Booking_Detail__r.Status__c = 'Booked'
                AND Booking_Detail__r.Start_Time__c >=: dt
               	ORDER BY Booking_Detail__r.Start_Time__c ASC];
    }
}