src/ConfRoomApp/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <label>Booking Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <label>Conference Room</label>
    <referenceTo>Conference_Room__c</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c  + ((VALUE(Text(Duration__c )) * 60) / 1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Booking_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/Conference_Room__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conference Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/ConfRoomApp/main/default/objects/Conference_Room__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <label>Resources</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Projector</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/ConfRoomApp/main/default/classes/ValidateBookingRecord.cls
public with sharing class ValidateBookingRecord {
    public ValidateBookingRecord() {

    }

     @AuraEnabled
     public static Boolean validateBookingRec(String confRoom, Datetime startTime, String duration){
         Boolean isOverlapFound = false;
         for(Booking_Detail__c rec :[ SELECT Id, Name, Conference_Room__c, Duration__c, Start_Time__c, 
                                            End_Time__C
                                        FROM Booking_Detail__c 
                                    	WHERE Conference_Room__c = :confRoom and
                                    Status__c = 'Booked']){
            
                if(confRoom == rec.Conference_Room__c  && (
                (startTime == rec.Start_Time__c) ||
                ( startTime > rec.Start_Time__c && startTime < rec.End_Time__c))){
                    isOverlapFound = true;
                    break;
                }
         }
         return isOverlapFound;
     }

    @AuraEnabled      
    public static Conference_Room__c fetchConfRoom( String recordId )  {   
          
        system.debug( 'Id is ' + recordId );  
        List < Conference_Room__c > listConfRooms = [ SELECT Id, Resources__c, Capacity__C FROM Conference_Room__c WHERE Id =: recordId LIMIT 1 ];  
          
        if( listConfRooms.size() > 0 )  
            return listConfRooms[0];  
        else  
            return null;  
          
    }  
}